[install]
# 使用隔离模式
linker = "isolated"


# 提升类型定义和工具到根目录
publicHoistPattern = [
    "@types/*",
    "prettier",
    "lerna",
    "ci-info",
    "vue-router",
    "tdesign-vue-next",
    "vite-bundle-analyzer",
]
